projects:
  - match: Lahar's Labor
    labels:
      - required: ["lahars-labor"]
  - match: Patches
    labels:
      - required: ["patch"]
  - match: Patches
    labels:
      - required: ["bug-in-clockwork"]
        whitelist: ["bug"]
      - required: ["bug-in-clockwork"]
        whitelist: ["bug"]
  - match: Patches
    labels:
      - required: ["patch-suggestion"]
  - match: Patches
    labels:
      - required: ["patch"]
