# If anything in /fomod is changed
fomod:
- "dist/fomod/**"

# If any esp/esl/esp file is changed
plugin-file-changes:
 - 'dist/Modules/**/*.esp'
 - 'dist/Modules/**/*.esm'
 - 'dist/Modules/**/*.esl'

# If any script files are changed
scripts:
 - 'dist/Modules/**/*.psc'
 - 'dist/Modules/**/*.pex'

# If any source files are changed
includes-non-functional:
 - 'dist/Modules/**/*.psc'
 - 'dist/Modules/**/dialogueviews/*.xml'

# If any assets are changed
asset-changes:
 - 'dist/**/*.dds'
 - 'dist/**/*.nif'
 - 'dist/**/*.xwm'
 - 'dist/**/*.png'
 - 'dist/**/*.jpg'
 - 'dist/**/*.webm'
