name: Patch Suggestion
description: Suggest a patch between Clockwork and another mod
title: '[B] TITLE HERE'
labels: ['suggestion', 'patch-suggestion']
assignees:
  - BellCube
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this patch suggestion!
  - type: input
    id: mod-name
    attributes:
      label: Mod Name
      description: Name of the mod
      placeholder: 'Example Mod™'
    validations:
      required: true
  - type: input
    id: mod-link
    attributes:
      label: Mod Link
      description: Link to the mod the item is from (preferably the Nexus page)
      placeholder: https://example.com
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: "What's Going On?"
      description: "What's not right between Clockwork and this mod?"
    validations:
      required: false
